apiVersion: apps/v1
kind: Deployment
metadata:
  name: goyin_chat_dep
spec:
  selector:
    matchLabels:
      app: goyin_chat
  replicas: 1
  template:
    metadata:
      labels:
        app: goyin_chat
    spec:
      containers:
        - name: goyin_chat
          image: violapioggia/goyin_chat
          ports:
            - containerPort: 10004
          volumeMounts:
            - name: goyin_chat_data
              mountPath: /tmp/  # 容器内的挂载路径
      volumes:
        - name: goyin_chat_data
          hostPath:
            path: /goyin/chat/  # 宿主机上的目录路径
---
apiVersion: v1
kind: Service
metadata:
  name: goyin_chat_svc
spec:
  ports:
    - name: goyin_chat
      port: 10004
      targetPort: 10004
  selector:
    app: goyin_chat
  type: ClusterIP