# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go 1.20

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./server/service/api/
           go build -v ./server/service/chat/
           go build -v ./server/service/interaction/
           go build -v ./server/service/sociality/
           go build -v ./server/service/user/
           go build -v ./server/service/video/

    - name: Test
      run: go build -v ./server/service/api/
           go build -v ./server/service/chat/
           go build -v ./server/service/interaction/
           go build -v ./server/service/sociality/
           go build -v ./server/service/user/
           go build -v ./server/service/video/
